spring:
  application:
    name: zuul
server:
  port: 9000
zuul:
  routes:
    contacto:
      path: /contacto/**
      serviceId: CONTACTO
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
      
ribbon: 
  ConnectTimeout: 3000
  ReadTimeout: 60000